### ISSUE TITLE
Add a contribution UI20CS74

### ISSUE THREAD

**Issue by zaidm124** [acm-svnit/kickstart-open-source#12]
Welcome to the world of Open-source!!
All the best with your first contribution.

Add the following details in the issue and create PR linking this
the issue in your commit:
1. (Zaid Bhimala) (UI20CS74)
2. Have you attended the Open-source event conducted by ACM? 
ans. Yes, i have attended the event conducted by ACM
3. If yes, what was your favorite part of the event? 
```
My favourite part was when we were being shown how to use github.
```
4. Will you continue contributing in Open-source? (Ans)Yes i will definitely contribute in open source.
5. Add a screenshot of the event here, if captured. (Drag and Drop here)

You are good to go!!

**Comment by pra17dod** [comment]
@zaidm124 Add your details in the Issue Description.

**Comment by zaidm124** [comment]
> @zaidm124 Add your details in the Issue Description.

I have added my details
