### ISSUE TITLE
Add Contribution UI20CS09

### ISSUE THREAD

**Issue by AryamanGurjar** [acm-svnit/kickstart-open-source#15]
Welcome to the world of Open-source!!
All the best with your first contribution.

Add the following details in the issue and create PR linking this
the issue in your commit:
1. (Name) (Roll number)
2. Have you attended the Open-source event conducted by ACM? (Ans)
3. If yes, what was your favorite part of the event? 
```
write here
```
4. Will you continue contributing in Open-source? (Ans)
5. Add a screenshot of the event here, if captured. (Drag and Drop here)

You are good to go!!

**Comment by pra17dod** [comment]
@AryamanGurjar Add your details in the Issue Description.

**Comment by AryamanGurjar** [comment]
1. Aryaman Gurjar
UI20CS09

2. Yes

3. When we got to know about GSOC how to participate in it, and how to search organisations for open source project.

**Comment by AryamanGurjar** [comment]
Done sir, 😅sorry i forgot to add that
