### ISSUE TITLE
UI20CS49

### ISSUE THREAD

**Issue by Naitik6803** [acm-svnit/kickstart-open-source#24]
Welcome to the world of Open-source!!
All the best with your first contribution.

Add the following details in the issue and create PR linking this
the issue in your commit:
1. (Name) (Roll number)
2. Have you attended the Open-source event conducted by ACM? (Ans)
3. If yes, what was your favorite part of the event? 
```
write here
```
4. Will you continue contributing in Open-source? (Ans)
5. Add a screenshot of the event here, if captured. (Drag and Drop here)

You are good to go!!

**Comment by pra17dod** [comment]
@Naitik6803 Add your details in the Issue Description.
